databases:
  - name: to-do-api
    databaseName: postgres
    user: postgres

services:
  - type: web
    name: to-do-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: to-do-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false